title: "Veille Technologique – OC"
description: "Dashboard de veille technologique structuré et automatisé pour OpenClassrooms"
remote_theme: just-the-docs/just-the-docs

search_enabled: true

repository_url: https://github.com/Escanor1986/veille_techno-OC

url: "https://escanor1986.github.io"
baseurl: "/veille_techno-OC"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

just_the_docs:
  custom_css: "assets/css/custom.css"
  favicon_ico: "/assets/images/favicon.webp"
