title: "Veille Technologique"
description: "Dashboard de veille technologique structuré et automatisé pour OpenClassrooms"
remote_theme: just-the-docs/just-the-docs

# Paramètres de recherche
search_enabled: true

# Configuration de la recherche
search:
  # Texte du placeholder dans la barre de recherche
  placeholder: "Rechercher..."
  # Texte affiché quand aucun résultat n'est trouvé
  no_results_text: "Aucun résultat trouvé"

# URL du dépôt et du site
url: "https://escanor1986.github.io"
baseurl: "/veille_techno-OC"
repository_url: https://github.com/Escanor1986/veille_techno-OC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme


# Thème et apparence
# Utiliser un schéma intégré au lieu d'un personnalisé
color_scheme: light
favicon_ico: "/assets/images/favicon.ico"

# Navigation et liens
aux_links:
  "GitHub":
    - "https://github.com/Escanor1986/veille_techno-OC"

# Paramètres supplémentaires
back_to_top: true
back_to_top_text: "Retour en haut"
