title: "Veille Technologique – OC"
description: "Dashboard de veille technologique structuré et automatisé pour OpenClassrooms"
remote_theme: just-the-docs/just-the-docs

# Paramètres de recherche
search_enabled: true

# URL du dépôt et du site
url: "https://escanor1986.github.io"
baseurl: "/veille_techno-OC"
repository_url: https://github.com/Escanor1986/veille_techno-OC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Thème et apparence
color_scheme: veille
favicon_ico: "/assets/images/favicon.ico"

# Navigation et liens
aux_links:
  "GitHub":
    - "https://github.com/Escanor1986/veille_techno-OC"

# Paramètres supplémentaires
back_to_top: true
back_to_top_text: "Retour en haut"

# Activation de l'inclusion de styles personnalisés
# Note: ceci est important pour que votre CSS personnalisé fonctionne
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
