name: Fetch RSS

on:
  schedule:
    - cron: "0 9 * * 1"  # chaque lundi à 9h UTC
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install rss-parser
        run: npm install rss-parser

      - name: Run fetch script
        run: node fetch-rss.js

      - name: Commit RSS update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add auto_*.md
          git commit -m "update: veille auto via RSS"
          git push
